### PR TITLE
message-dictionary: Specify encoding (hex or dec) for some values

### PR DESCRIPTION
**Pull request by hillu**
These changes are based on reviewing relevant source code from Linux 5.13.

Signed-off-by: Hilko Bengen <bengen@hilluzination.de>

### CODE REVIEW

**Comment by rgbriggs** [comment]
On 2021-07-02 12:32, Hilko Bengen wrote:
>   * message-dictionary: Specify encoding (hex or dec) for some values

This looks like a very helpful change, Thank you.

This looks like a typo: "deimal" should be "decimal":
+res,numeric deimal,result of the audited operation(success/fail),

dev/rdev could be listed as hexadecimal, but it isn't a pure format,
containing a colon between major and minor numbers.  What record types
had "major=" and "minor=" fields?

I'm a bit surprised that cap_fe and fe are decimal, but it is in the
source code!  Similarly I expected cap_fver and fver to be decimal but
it is hex!

The mmap flags are hex.

**Comment by hillu** [comment]
major, minor are from `tty_audit_log`. For some reason I wasn't 100% sure about the mmap flags. Corrected the typo.

**Comment by rgbriggs** [comment]
On 2021-07-02 19:34, Hilko Bengen wrote:
> major, minor are from `tty_audit_log`. For some reason I wasn't 100% sure about the mmap flags. Corrected the typo.

Ok, I see that from tty_audit_log().  Too late to change major=/minor= over to dev=major:minor now since it has been years and we don't want to break userspace.

The mmap flags is still decimal when it should be hex.

**Comment by hillu** [comment]
> The mmap flags is still decimal when it should be hex.
I have verified that it should be hex and fixed it.

I think I'd call the colon-separated hex values for dev and rdev a tuple…

**Comment by rgbriggs** [comment]
On 2021-07-04 05:53, Hilko Bengen wrote:
> > The mmap flags is still decimal when it should be hex.
> I have verified that it should be hex and fixed it.

Looks better.

> I think I'd call the colon-separated hex values for dev and rdev a tuple…

Agreed.

**Comment by hillu** [comment]
Would you like to merge or should I make a change to `dev` and `rdev`, resulting in `numeric hexadecimal-tuple` ?

**Comment by rgbriggs** [comment]
On 2021-07-10 06:22, Hilko Bengen wrote:
>    Would you like to merge or should I make a change to dev and rdev, resulting in numeric hexadecimal-tuple ?

I like your "numeric hexadecimal-tuple" idea.  Please add it since there have been no other comments.

**Comment by hillu** [comment]
@rgbriggs Would you like to merge or is there anything else I should address?

**Comment by pcmoore** [comment]
FWIW, this looks good to me, what do you say about the current version @rgbriggs ?

**Comment by rgbriggs** [comment]
On 2021-07-19 19:43, Paul Moore wrote:
>    FWIW, this looks good to me, what do you say about the current version @rgbriggs ?

Looks good to me.  I guess I have perms on this repo to have approved it...

**Comment by pcmoore** [comment]
You should have the right GH access rights to commit to the repo too, want to give it a shot to make sure it works?

`Reviewed-by: Paul Moore <paul@paul-moore.com>`

**Pull request merged**
