### PR TITLE
RFE: update message types for Linux 5.16-rc6

### PR DESCRIPTION
**Pull request by hillu**

### CODE REVIEW

**Comment by pcmoore** [comment]
Hi @hillu, thanks for the patch.  Would you mind adding a sign-off line to the commit description as described in the [CONTRIBUTING.md](https://github.com/linux-audit/audit-documentation/blob/main/CONTRIBUTING.md) doc?

**Comment by hillu** [comment]
@pcmoore Done.

**Comment by hillu** [comment]
(for real now.)

**Comment by pcmoore** [comment]
Merged via b5a76394e165b104c95c94127ac3d29eed68f927, thanks!

**Pull request closed without merging**
